default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: D_scene_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: D_scene_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: D_scene_prod
  pool: 5
  timeout: 5000
